### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by agoulart929** [wheaney/decky-XRGaming#22] opened 2024-08-21 23:23 UTC
I repeatedly get the message "There was an error during setup. Try restarting your Steam Deck. If the error persists, please file an issue in the decky-XRGaming GitHub repository." Restarting does not resolve the issue.

**Comment by wheaney** [comment] 2024-08-22 00:10
Are you using the test store version by chance? Starts with v0.11

**Comment by agoulart929** [comment] 2024-08-22 00:50
I'm not, I'm using v0.9.7.2 from the default store.

**Comment by wheaney** [comment] 2024-08-22 00:58
Can you attach the logs in `~/homebrew/logs/decky-XRGaming/` and `~/.xreal_driver_log`

**Comment by agoulart929** [comment] 2024-08-22 14:22
I'll try to get that to you later tonight. By the way, thanks for being so
fast and responsive!

**Comment by agoulart929** [comment] 2024-08-23 13:01
Here are the logs you asked for. I was unable to find the .xreal_driver_log

**Comment by wheaney** [comment] 2024-08-26 21:02
@agoulart929 I don't see that the logs came through in your most recent comment.

**Comment by agoulart929** [comment] 2024-08-26 23:25
I replied directly through email, the files are attached to the email.

**Comment by wheaney** [comment] 2024-08-30 03:17
I don't think you can attach files like that, it didn't come through in the email (no attachments). Can you upload them here?

**Comment by agoulart929** [comment] 2024-08-30 13:41
Ok, here are the logs.
[2024-08-21 20.48.57.log](https://github.com/user-attachments/files/16817878/2024-08-21.20.48.57.log)
[2024-08-21 19.41.37.log](https://github.com/user-attachments/files/16817884/2024-08-21.19.41.37.log)
[2024-08-21 19.41.18.log](https://github.com/user-attachments/files/16817890/2024-08-21.19.41.18.log)
[2024-08-21 19.41.17.log](https://github.com/user-attachments/files/16817893/2024-08-21.19.41.17.log)
[2024-08-21 19.40.30.log](https://github.com/user-attachments/files/16817895/2024-08-21.19.40.30.log)

**Comment by wheaney** [comment] 2024-08-30 15:03
The error you're running into could have only been caused by v0.11 AFAIK. Maybe you tried installing that version and then reverted back but it left a file behind that breaks this install? Anyway, the fix is to `rm ~/bin` and the root cause is already resolved in the version of decky that's awaiting release.

**Comment by agoulart929** [comment] 2024-08-30 15:34
Sorry I'm not great with computers. What do you mean by rm ~ bin? For you
mean type that into the konsole?

**Comment by wheaney** [comment] 2024-08-30 15:36
Yeah, in the Konsole then reinstall.

**Comment by agoulart929** [comment] 2024-08-30 15:39
Awesome, thank you for the help!

**Comment by boludo00** [comment] 2024-08-30 20:47
Hey! I am getting a similar error as well. I had installed using the default store and XR Gaming version 

I am getting a `Could not find state file at /dev/shm/xr_driver_state`. 
There is also a log that says `Setting up the systemd service\nsystemd startup failed`.

**Comment by wheaney** [comment] 2024-08-30 21:02
@boludo00 it's not the same error unless you're seeing `mkdir: cannot create directory '/home/deck/bin': File exists`. basically the setup script is failing because ~/bin already exists as a file and not a directory, which is why the solution is to remove that file. Can you please file a new issue or open a #troubleshooting thread in my Discord?

**Comment by wheaney** [comment] 2024-08-30 21:02
@agoulart929 I think your issue got resolved, so I'm going to close this out. Please reopen if it's still ongoing.

**Closed by wheaney** 2024-08-30 21:02 UTC
