### ISSUE TITLE
Is it possible to add IPD (interpupillary distance) adjustment?

### ISSUE THREAD

**Issue by KirillArtemenko** [wheaney/decky-XRGaming#19] opened 2024-07-23 09:02 UTC
Is it possible to add IPD (interpupillary distance) adjustment capabilities?

P.S. I have just begun to study this plugin and all its capabilities; I am not yet very familiar with the limitations on the ability to control image output on glasses. Thanks for the great job!

**Comment by wheaney** [comment] 2024-07-23 19:53
Typically when we talk about IPD with respect to these glasses, we're talking about a range of IPDs that the glasses are built for. If you're having issues related to IPD, it's probably related to that optimal range for the glasses. That range is driven by a physical requirement of the glasses, specifically how the fishbowl lenses are positioned. My plugin can't fix issues related to physical lens placement.

With all that out of the way, my plugin does have the ability to control spacing between the images in SBS mode. This won't fix blurriness or other visual issues caused by the physical aspects of IPD issues as described above, but it can maybe make it a little more comfortable or possibly even place the images more into a sweet spot in the lenses, if there is one. To test that out, you'd enable side-by-side mode (advanced options in Virtual Display mode), and play with the display distance. A closer distance will pull the images closer to your nose, and a farther distance will push the images slightly further away from your nose. This won't work in any other mode.

I'm gonna close out this issue since there's nothing more I can do to address it. But feel free to drop in the Discord if you have more questions.

**Closed by wheaney** 2024-07-23 19:53 UTC

**Comment by KirillArtemenko** [comment] 2024-07-24 09:04
Yes, this is exactly what I was looking for. I of course mean software IPD, not physical. Thanks for the tip about additional options in Virtual Display mode! I'll definitely check this mode out.
