### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by travbp** [wheaney/decky-XRGaming#36] opened 2024-12-09 14:46 UTC
Getting the error that there was an issue during the install of v1.0.2.

Using the Viture Pro XR and latest Stable version of Decky.

**Comment by wheaney** [comment] 2024-12-09 18:26
Hi @travbp or @silarsis can one of you please provide me with the logs at `/home/deck/homebrew/logs/decky-XRGaming`

**Comment by travbp** [comment] 2024-12-09 18:31
[2024-12-09 08.36.27.log](https://github.com/user-attachments/files/18066174/2024-12-09.08.36.27.log)
[2024-12-09 10.59.46.log](https://github.com/user-attachments/files/18066175/2024-12-09.10.59.46.log)
[2024-12-09 11.11.38.log](https://github.com/user-attachments/files/18066176/2024-12-09.11.11.38.log)
[2024-12-09 11.19.10.log](https://github.com/user-attachments/files/18066177/2024-12-09.11.19.10.log)
[2024-12-09 12.27.54.log](https://github.com/user-attachments/files/18066178/2024-12-09.12.27.54.log)

**Comment by wheaney** [comment] 2024-12-09 18:39
You said you're on the `stable` decky channel, and what SteamOS channel are you on?

**Comment by travbp** [comment] 2024-12-09 18:40
Beta

**Comment by wheaney** [comment] 2024-12-09 18:43
One rule-of-thumb with decky loader is you should match channels with SteamOS, so for SteamOS Stable you should be in the `Stable` decky loader channel, and for SteamOS Beta/Preview you should be in the `Prerelease` decky loader channel. Can you see if switching to that fixes the install for v1.0.2 of my plugin?

**Comment by travbp** [comment] 2024-12-09 19:18
[2024-12-09 13.15.59.log](https://github.com/user-attachments/files/18066927/2024-12-09.13.15.59.log)
[2024-12-09 13.15.53.log](https://github.com/user-attachments/files/18066928/2024-12-09.13.15.53.log)
[2024-12-09 12.27.54.log](https://github.com/user-attachments/files/18066929/2024-12-09.12.27.54.log)

**Comment by travbp** [comment] 2024-12-09 19:19
Switched to prelease update channel on Decky to match SteamOS beta, and it's back to the same error. Previous comment has the log files that were modified

**Comment by wheaney** [comment] 2024-12-09 19:42
One weird thing I see in that log is this command appears to be producing some weird output, can you try running it yourself if you have SSH access? You could also try from Konsole in desktop mode, you'll need to enter a sudo password: `su -l -c 'XDG_RUNTIME_DIR=/run/user/1000 systemctl --user is-active xr-driver' deck`

**Comment by wheaney** [comment] 2024-12-09 19:45
I've tried to reproduce this myself using Stable/Stable and Beta/Prerelease and everything has worked fine for me. I also see that the above command returns `active` for me as expected, while yours returned `xhost:  unable to open display ""\ninactive\n`. What other plugins or mods have you installed on this system, and have you done any other tinkering on it or is it otherwise "stock?"

**Comment by travbp** [comment] 2024-12-09 20:05
Hmm, I’ve tinkered with it a good amount, but nothing related to the
drivers or display that I’m aware of! I do have the following decky
plug-ins installed as well:

Pause Games
ProtonDB Badges
Auto flat oaks
Storage Cleaner
MoonDeck
PowerTools

**Comment by travbp** [comment] 2024-12-09 20:12
```
xhost:  unable to open display ""
active
```
Is the output of the posted command

**Comment by travbp** [comment] 2024-12-09 20:14
Does it matter whether or not I have the glasses plugged in when installing the plugin and/or running these tests? They are not currently plugged in

**Comment by travbp** [comment] 2024-12-09 20:40
#
# ~/.bashrc
#
export PATH=$HOME/.local/bin:$PATH

export PATH=$HOME/.local/podman/bin:$PATH

xhost +si:localuser:$USER

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

**Comment by travbp** [comment] 2024-12-09 20:41
Ahh okay! Here is the contents of my bashrc

**Comment by wheaney** [comment] 2024-12-09 20:42
`xhost +si:localuser:$USER` looks like the problematic line

**Comment by travbp** [comment] 2024-12-09 20:45
Awesome, I axed that line and it works now! Now to see what I broke by removing it 😂

**Comment by wheaney** [comment] 2024-12-09 20:45
Actually I'm betting this line was meant to prevent this:
```
# If not running interactively, don't do anything
[[ $- != *i* ]] && return
```

You would just want to put that BEFORE the `xhost` command so it would return early.

**Comment by travbp** [comment] 2024-12-09 20:50
Ahh okay, I reordered them and it works as well! Thanks again :)

**Comment by wheaney** [comment] 2024-12-09 20:53
Phew, glad it wasn't really an issue with my plugin's setup. 

I'm going to close this out, but @silarsis if you come across this, see if you can grab those logs and try running `su -l -c 'XDG_RUNTIME_DIR=/run/user/1000 systemctl --user is-active xr-driver' deck` from a terminal to see what your output is.

**Closed by wheaney** 2024-12-09 20:53 UTC

**Comment by silarsis** [comment] 2024-12-09 23:45
Before getting the logs I can tell you that yes, I have extra output in my bashrc, so that's likely the cause. Will debug now and see

**Comment by silarsis** [comment] 2024-12-09 23:51
confirmed - I had a tailscale setup with some aliases and output in bashrc to remind me what to type, and ensuring that doesn't print out has meant it's working again. Thanks :)
